# Permalinks
permalink:

# Setup
title: Gymnasium CMS
#url: "http://gymnasium.github.io/cms/"
baseurl: /cms  # This makes the index page URL localhost:4000/cms/ Remember: Omit the trailing slash!

collections:
    events:
        output: true
        permalink: /cms/events/


repository: gymnasium/cms
